[package]
name = "libcontainerd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
time = "0.3"
tokio = { version = "1.21", features = ["rt"] }